parameters:
    hgabka_kunstmaan_banner.banner_handler.class: 'Hgabka\KunstmaanBannerBundle\Helper\BannerHandler'

services:
    hgabka_kunstmaan_banner.banner_handler:
        class: '%hgabka_kunstmaan_banner.banner_handler.class%'
        arguments: ["@doctrine", "@hgabka_kunstmaan_extension.kuma_utils", ""]

    hgabka_kunstmaan_banner.banner_type:
        class: Hgabka\KunstmaanBannerBundle\Form\BannerAdminType
        arguments: ['@hgabka_kunstmaan_banner.banner_handler', "@router"]
        tags:
            - { name: form.type }

    hgabka_kunstmaan_banner.menu.adaptor.banner:
        class: Hgabka\KunstmaanBannerBundle\Helper\Menu\BannerMenuAdaptor
        arguments: ['@security.authorization_checker', '']
        tags:
            -  { name: kunstmaan_admin.menu.adaptor }

    hgabka_kunstmaan_banner.banner_twig_extension:
        class: Hgabka\KunstmaanBannerBundle\Twig\HgabkaKunstmaanBannerTwigExtension
        arguments: ['@hgabka_kunstmaan_banner.banner_handler']
        public: false
        tags:
            - { name: twig.extension }

    hgabka_kunstmaan_banner.banner_voter:
        class:  Hgabka\KunstmaanBannerBundle\Security\BannerVoter
        arguments: ['@security.access.decision_manager', '']
        tags:
            - { name: security.voter }
        public: false